[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "sql"
    version = "@project.version@"
    path = "./lib/ballerina-sql-@project.version@.jar"
    groupId = "ballerina"
    modules = ["sql"]

    [[platform.libraries]]
    artifactId = "HikariCP"
    version = "3.3.1"
    path = "./lib/HikariCP-3.3.1.jar"
    groupId = "com.zaxxer"
    modules = ["jdbc"]
