[project]
org-name = "ballerina"
version = "0.6.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "java.mail"
    version = "1.6.2"
    path = "./lib/javax.mail-1.6.2.jar"
    groupId = "javax.mail"
    modules = ["email"]

    [[platform.libraries]]
    artifactId = "email"
    version = "@project.version@"
    path = "./lib/ballerina-email-@project.version@.jar"
    groupId = "ballerina"
    modules = ["email"]
